/**
 * User data interface for system-wide type safety
 * Updated for PostgreSQL/Prisma compatibility (using 'id' instead of '_id')
 */
export interface IUser {
  id: string;              // Unique UUID generated by Postgres
  name: string;            // User's full display name
  email: string;           // Login and identification email
  bio: string | null;      // Optional short biography
  password?: string;       // Hashed password (optional in responses for security)
  role: "student" | "admin"; // Restricted roles system
  avatar?: string | null;  // URL to student profile image
  createdAt: Date;         // System timestamp for user creation
  updatedAt: Date;         // System timestamp for latest profile update
}

/**
 * Interface representing user credentials required for login
 */
export interface IUserLogin {
  email: string;           // Target account email address
  password: string;        // Raw password to be verified against hash
}
